name: Kotlin CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Access ./gradlew file
      run: chmod +x ./gradlew
    - name: Build and Test
      run: ./gradlew test
